station;

CREATE TABLE `station`(

`id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,

`name` VARCHAR(50)NOT NULL,

`created_at` TIMESTAMP NOT NULL DEFAULT NOW,
`updated_at` TIMESTAMP NOT NULL DEFAULT NOW,

PRIMARY KEY (id)
)
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_unicode_ci;

